### ISSUE TITLE
Question sur ?count=500 (format= Pas fonctionel)

### ISSUE THREAD

**Issue by Stephanevg** [regardscitoyens/nosdeputes.fr#100]
Hello :)

Une petite question (encore ^^)

Le ?count=500 est elle destiné a tous les elements de la recherche? Ou sers-t-ell uniquement à gérer la pagination sur les recherches qui incluent "object_type=" ?

La requete suivante me retourne pas le document au format xml, mais en full html.

https://www.nosdeputes.fr/recherche/cumul?count=500?format=xml

De cette manière j'ai le même comportement:

https://www.nosdeputes.fr/recherche/cumul?format=xml?count=500

C'est peut être voulu pour une raison qui m'échappe? 

Et de manière plus générale, est ce que le 'count=' peut être rajouté n'importe ou dans la query, ou doit elle toujours ce trouver en fin de query?

**Comment by RouxRC** [comment]
Euh là non, tu ne connais apparemment pas bien le fonctionnement des urls et tu as mal regardé les autres exemples dans la doc désolé :p 
Je te propose de lire https://en.wikipedia.org/wiki/Query_string#Structure et de relire ta question ;)
