### ISSUE TITLE
API - Étrange réponse pour /amendements/

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#101]
Pour trouver les amendments sur [ce texte](http://www.assemblee-nationale.fr/15/projets/pl0235.asp), [qui existent bien](http://www2.assemblee-nationale.fr/recherche/amendements/15#listeResultats=tru&idDossierLegislatif=35854&idExamen=327&missionVisee=&numAmend=&idAuteur=&premierSignataire=true&idArticle=&idAlinea=&sort=&dateDebut=&dateFin=&periodeParlementaire=&texteRecherche=&zoneRecherche=tout&nbres=10&format=html&regleTri=ordre_texte&ordreTri=croissant&start=1), j'utilise cette url:

```
https://nosdeputes.fr/15/amendements/235/json
```

Mais la réponse est une page blanche, peut-être un problème au niveau mémoire ?

(EDIT: similaire à #90)

**Comment by boogheta** [comment]
This is due to the limit of 65Mo of ram per request where this batch of amendements  requires more than 300mo because there are 4910 amendements
I've harcached it as we did earlier for https://www.nossenateurs.fr/seance/1323/20082009-553/json

**Comment by mdamien** [comment]
Sur cet exemple, c'est assez aléatoire mais ca renvoi souvent un 500: https://www.nossenateurs.fr/seance/12774/20142015-371/json

**Comment by boogheta** [comment]
hardcached and added a script to simplify generating such caches here https://github.com/regardscitoyens/nosdeputes.fr/commit/846f58b04cd4fb9dd42b244fd070b5117121ea87
