### ISSUE TITLE
Discussion retour recherche via l'API

### ISSUE THREAD

**Issue by Stephanevg** [regardscitoyens/nosdeputes.fr#102]
Hello,

En finalisant une fonciton pour lire executer des recherches sur l'API via PowerShell, je me posais la question si cela pouvait ëtre interessant pour un utilisateur qui utilise la fonction de recherche via l'API d'avoir un peu plus de contexte sur ce que finalement chaque résultat représente?

## Exemple

Pour la recherche suivante:

https://www.nosdeputes.fr/recherche/?object_name=Texteloi&count=500

La recherche via l'interface retourne les résultats suivants:

![image](https://user-images.githubusercontent.com/6302961/36438354-f47f7d86-1669-11e8-8bde-5b4930467bd3.png)

Et pour la même recherche via l'API au format XML:

(url --> rhttps://www.nosdeputes.fr/recherche/?object_name=Texteloi&Format=XML&count=500 )

![image](https://user-images.githubusercontent.com/6302961/36438445-3efd3506-166a-11e8-92f1-894029f75b59.png)

Via PowerShell j'ai par exmemple le retour suivant (Après un traitement minimal):

![image](https://user-images.githubusercontent.com/6302961/36441934-66f5389c-1674-11e8-853f-e722b64cc778.png)

En regardant les résultats, je me disait qu'un court 'extrait' du résultat pouvait être interessant à avoir, car on ne sait rien des données finalement qui sont retournées. (La ou avec l'interface on a toujours un tres court extrait).

Après, on peut ce poser la question suivante: Est-ce qu'une API ce doit de retourner un peu plus d'information? Est-ce qu'il ne risque pas de devenir justement 'trop verbeux'?

Qu'en pensez vous?

**Comment by RouxRC** [comment]
Oui clairement ça fait partie des améliorations assez prioritaires de l'API à mes yeux, en l'état les résultats sont vraiment hyper légers

**Comment by teymour** [comment]
c9f6296a ajoute les champs directement accessible depuis Solr.

**Comment by revolunet** [comment]
du coup c'est réglé ?

**Comment by RouxRC** [comment]
yep, le minimum dispo est bien renvoyé désormais en effet https://www.nosdeputes.fr/recherche/?object_name=Texteloi&count=500&format=xml
