### ISSUE TITLE
Interventions - section manquante

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#103]
Dans cette intervention, la section sur le pouvoir d'achat n'a pas été détéctée comme telle: https://2007-2012.nosdeputes.fr/seance/4988#inter_a3101a8275d990e545cfdcbc2f3d1ab0

Ca résulte en des interventions sans sections dans l'api (`soussection: null,`): https://2007-2012.nosdeputes.fr/seance/4988/3403/json?textplain=1

C'est vraiment pas prioritaire et c'est de la fouille archéologique mais c'est a noter :)

**Comment by boogheta** [comment]
yep good catch !
But won't fix, too late ;)
