### ISSUE TITLE
RegardsCitoyenPS

### ISSUE THREAD

**Issue by Stephanevg** [regardscitoyens/nosdeputes.fr#104]
Hello, c'est encore moi ;)

Cette fois ci, j'écris un peu pour autre chose. J'ai pas mal bosser avec votre API, que je trouves vraiment top. 

Du coup, j'ai pris un peu de temps et j'ai écris un Module PowerShell qui permet l'accès aux données via vôtre API directement depuis un prompt PowerShell (Dispo sur Windows - Mac et Linux). 

Le projet est disponible ici --> https://github.com/Stephanevg/RegardsCitoyenPS/ 
Et j'en parle sur mon blog ici (Article que je compte updater avec les details technique pour la mise en place du module) --> http://powershelldistrict.com/introduction-regardscitoyenps/ 

Sur les deux liens il y a pas mal d'explications sur comment commencer etc...

Je pensais peut être faire un fork/PR de votre readme.md et mettre un lien vers le projet et l'article du blog. Ca serait ok pour vous?

Si vous avez des remarques / suggestions je suis preneur!

Stéphane

**Comment by RouxRC** [comment]
Avec plaisir ! Il y a une section dédiée dans la doc de l'API dont une qui pointe un projet semblable (mais moins abouti) en python, le tien aurait toute sa place à côté : https://github.com/regardscitoyens/nosdeputes.fr/blob/master/doc/api.md#librairie-python-cpc-api

**Comment by Stephanevg** [comment]
Cool!

Voici le PR -> https://github.com/regardscitoyens/nosdeputes.fr/pull/105 

;)

**Comment by Stephanevg** [comment]
Hello, 

je dois modifier quelque chose au PR? (Ou suis-je juste trop pressé? ;))

**Comment by Stephanevg** [comment]
Hello, j'ai poussé un PR il y a 6 jours. Sais tu @RouxRC pk il bloque? (Ou suis-je tout simplement un peu trop impatient?)

**Comment by RouxRC** [comment]
Salut, juste trop impatient oui, RC est entièrement bénévole ;)
Le point de @teymour sur la licence était juste, merci de l'avoir géré.
Par ailleurs, il reste quelques fautes d'orthographe et je pense plus généralement qu'il n'est pas nécessaire de préciser les détails d'installation et de bugreport. Comme pour cpc-api, le lien vers le repo avec une courte description me semblerait plus équilibré. J'essaierai d'itérer ce week-end si tu ne l'as pas déjà fait :)

**Comment by Stephanevg** [comment]
Hello, 
Voila j'ai raccourcis et corriger les petites fautes --> https://github.com/regardscitoyens/nosdeputes.fr/pull/105

**Comment by RouxRC** [comment]
Et voilà c'est mergé, merci, j'ai légèrement retouché et t'ai pointé comme auteur :)
Vu que tu l'as changé dans le texte, tu peux aussi changer le nom de ton repo pour ajouter le s manquant en éditant les settings si tu veux, github gère tout seul les redirections ensuite.
