### ISSUE TITLE
Lighten ram used by API route for amendments by law

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#109]
(comme signalé sur IRC, je le met ici pour faciliter le suivi)

Le point d'API: https://nosdeputes.fr/15/amendements/714/json?cache=1523958383
Le dossier: http://www.assemblee-nationale.fr/15/dossiers/immigration_maitrisee_droit_asile_effectif.asp

**Comment by boogheta** [comment]
harcached

**Comment by boogheta** [comment]
Although, worth investigating why on earth these only 64 amendments are sufficient to overload the ram

**Comment by boogheta** [comment]
it looks like it comes from requesting all MPs of each amendment (to populate their slugs and groups) and it doesn't seem like we can optimize it better as such.
A possible solution could be to add a specific light route which returns less data that could be queriable directly in the first query, for instance with a max(count(distinct(parlementaire_groupe_acronyme))) or such

**Comment by mdamien** [comment]
To continue on the tradition, another example of a 500: https://nosdeputes.fr/15/amendements/857/json
Strangely, it works well on the website: https://www.nosdeputes.fr/15/amendements/857/all

I agree completely on lightening the response with only things needed

**Comment by RouxRC** [comment]
same text, makes sense ! :) hardcached as well!
also makes sense it works in the frontend as the queries are totally different (and paginated ;) )

**Comment by mdamien** [comment]
Thanks, I also found the same thing for the PJLF2018: https://www.nosdeputes.fr/15/amendements/485/json (good news is the PJLF parsing works !)

**Comment by boogheta** [comment]
hardcached

**Comment by mdamien** [comment]
bad news, there's still some RAM issues: https://www.nosdeputes.fr/15/amendements/627/json , 1927 amendments !

**Comment by boogheta** [comment]
I don't have much more ideas to lighten it more without removing slugs or starting to paginate which is overkill as for now if the fix only requires one hardache once in a while.
So I hardcached this one as well ! :)

**Comment by mdamien** [comment]
maybe we should try to paginate ? I just got the same error for the same text, this time it's 2430 amendments in hemicycle:

 - text: http://www.assemblee-nationale.fr/dyn/15/dossiers/equilibre_relations_commerciales_agriculture?etape=15-AN1
 - api endpoint: https://www.nosdeputes.fr/15/amendements/902/json

**Comment by mdamien** [comment]
Also I believe the previously cached amendments are now obsolete because of the last API change

EDIT: oops, no, it was my fault, using the same "cache=XXX" argument

**Comment by mdamien** [comment]
I've just found two new cases of 500:

- https://www.nosdeputes.fr/15/amendements/911/json (reforme constit) (http://www.assemblee-nationale.fr/15/projets/pl0904.asp)
- https://www.nosdeputes.fr/15/amendements/1019/json (avenir pro) (http://www.assemblee-nationale.fr/15/ta-commission/r1019-a0.asp)

**Comment by RouxRC** [comment]
hardcached, and redid it for all the previous ones to handle potential mp name changes
