### ISSUE TITLE
"Liasse" link for amendments not working

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#111]
ex: https://www.nosdeputes.fr/15/amendements/857/all

Current link (not working): [http://recherche2.assemblee-nationale.fr/amendements/resultats.jsp?typeEcran=avance&chercherDateParNumero=non&NUM_INIT=857-......](http://recherche2.assemblee-nationale.fr/amendements/resultats.jsp?typeEcran=avance&chercherDateParNumero=non&NUM_INIT=857-a0&NUM_AMEND=&AUTEUR=&DESIGNATION_ARTICLE=&DESIGNATION_ALINEA=&SORT_EN_SEANCE=&DELIBERATION=&NUM_PARTIE=&DateDebut=&DateFin=&periode=&LEGISLATURE=15Amendements&QueryText=&Scope=TEXTEINTEGRAL&SortField=ORDRE_TEXTE&SortOrder=Asc&format=PDF&searchadvanced=Rechercher)
Working link: [http://www2.assemblee-nationale.fr/recherche/amendements#....](http://www2.assemblee-nationale.fr/recherche/amendements/15#listeResultats=tru&idDossierLegislatif=36410&idExamen=1144&missionVisee=&numAmend=&idAuteur=&premierSignataire=true&idArticle=&idAlinea=&sort=&dateDebut=&dateFin=&periodeParlementaire=&texteRecherche=&zoneRecherche=tout&nbres=10&format=html&regleTri=ordre_texte&ordreTri=croissant&start=1)

We compute the liasse url here: https://github.com/regardscitoyens/nosdeputes.fr/blob/5f40af02134f9443493a2521f1d1d92eb7a93849/lib/model/doctrine/myTools.class.php#L315

**Comment by RouxRC** [comment]
on a pas accès aux ids des lectures nécessaires pour forger ces url depuis les données en base dans ND malheureusement, je commente le lien du coup
