### ISSUE TITLE
widget des députés  avec leurs activités

### ISSUE THREAD

**Issue by aminewebonline** [regardscitoyens/nosdeputes.fr#119]
Bonjour,
j'essaie d'intégrer le widget concernant un député  en donnant le nom de famille comme paramètre au widget mais des fois ça et des fois non :

pour Franck Riester ca fonctionne 
<?php
 echo file_get_contents('http://www.nosdeputes.fr/widget/Riester?maxtags=15');
?>

qu'est ce qu'on donne exactement comme paramètre ? le nom de famille  ou le slug

**Comment by boogheta** [comment]
bonjour, c'est indiqué ici : https://github.com/regardscitoyens/nosdeputes.fr/blob/master/doc/widget.md#acc%C3%A8s
le nom de famille peut fonctionner dans certains cas, mais l'usage correct est le slug

**Comment by aminewebonline** [comment]
oui, j'ai vu, mais dans la plupart des cas, ça fonctionne pas
par exemple pour  les slugs suivants : 
nicole-trisse
martine-wonner
annaig-le-meur

c'est des slugs récupérés depuis le csv que  vous avez mis sur votre api

**Comment by boogheta** [comment]
Ah c'est étrange, ça ne devrait pas et je ne le constate pas en testant avec ces cas, par exemple : https://www.nosdeputes.fr/widget15/nicole-trisse?iframe=true&notags=1&width=580

Pourriez-vous préciser vos cas d'usage?

**Comment by aminewebonline** [comment]
c'est bon ça fonctionne, 
j'utilisais widget14/ à la place de widget15/
Merci beaucoup
