### ISSUE TITLE
l'url à donner pour avoir le graphe pour un sénateur donné

### ISSUE THREAD

**Issue by aminewebonline** [regardscitoyens/nosdeputes.fr#120]
Bonjour, j'essaie d'afficher le le widget pour un sénateur donné mais ca fonctionne pas,
je sais pas si le lien fournit en paramètre est correct ?
Merci

<?php
echo file_get_contents('https://www.nossenateurs.fr/widget15/'.$senateur->slug.'?iframe=true&notags=1&height=150');
?>

**Comment by RouxRC** [comment]
Le widget n'est pas encore disponible pour NosSénateurs.fr, il n'a été implémenté que sur NosDéputés.fr.
C'était indiqué uniquement sur la [doc de l'API](https://github.com/regardscitoyens/nosdeputes.fr/blob/master/doc/api.md#d%C3%A9tails-de-chaque-parlementaire), je l'ai ajouté également sur la [doc du widget](https://github.com/regardscitoyens/nosdeputes.fr/blob/master/doc/widget.md#widget-de-lactivit%C3%A9-dun-parlementaire) du coup.

**Comment by aminewebonline** [comment]
ok merci
