### ISSUE TITLE
Avoir les details des votes des députés

### ISSUE THREAD

**Issue by MalcolmMielle** [regardscitoyens/nosdeputes.fr#125]
Bonjour, 

Je n'arrive pas a savoir en lisant l*API si il y a un moyen d'obtenir les details des votes des deputés. Dans le sens, savoir si ils ont voté "pour ou contre ou abstension" avec la listes associé des reference de lois.

Dans l'autre sens, avoir une liste de references de lois et comment chaque deputés a voté pour celle ci serait aussi benefique :)

Merci,

**Comment by RouxRC** [comment]
Bonjour,

Les données des votes ont commencé à être intégrées, mais elles ne sont à ce jour utilisées que pour détecter la présence des députés lors de séances en hémicycle. L'accès au détail des votes individuels des députés n'est pas encore possible, ni sur le site, ni via l'API.
Notre programme de travail à ce sujet est ici : #121
