### ISSUE TITLE
Députés hors mandat lors de l'extraction en MMAAAA

### ISSUE THREAD

**Issue by besnarda** [regardscitoyens/nosdeputes.fr#126]
Merci pour votre travail, j'ai repéré que lors d'une extraction en mois année de l'activité parlementaire (par exemple pour le mois de juillet 2019 https://www.nosdeputes.fr/synthese/201907/csv ) Des députés qui ont terminé leur mandat sont encore dans le tableau. Ex: Olivier Dussopt ou Frank Riester ou encore Isabelle Muller-Quoy. Aucune activité n'est enregistré pour eux (0 partout) ni aucun groupe.

**Comment by RouxRC** [comment]
Bonjour Alban et merci de ce retour. Ce comportement est cependant un choix volontaire : ces routes renvoient pour chaque mois les données disponibles pour l'ensemble des parlementaires ayant exercé ne serait-ce que quelques jours durant la législature, afin de permettre d'assembler plus simplement les données de plusieurs mois collectées à un même instant. Mais il est assez aisé à partir des champs anciens_mandats, debut_mandat et fin_mandat de la route renvoyant les métadonnées de chaque parlementaire <https://www.nosdeputes.fr/deputes/csv> de procéder aux filtrages que vous souhaitez
