### ISSUE TITLE
Questions des sénateurs

### ISSUE THREAD

**Issue by malex18** [regardscitoyens/nosdeputes.fr#134]
Bonjour, 

Pour récupérer les questions des députés et sénateurs il faut normalement passer par le moteur de recherche et filtrer sur l'object en utilisant QuestionEcrite (See Filtrage / type d'objet -> https://github.com/regardscitoyens/nosdeputes.fr/blob/master/doc/api.md#r%C3%A9sultats-du-moteur-de-recherche).

Cela fonctionne très bien pour nos députés mais pour nos sénateurs l'object_name n'est pas QuestionEcrite mais Question.

**Nos Députés**
https://www.nosdeputes.fr/recherche/?object_name=QuestionEcrite&format=xml

**Nos Sénateurs**:
https://www.nossenateurs.fr/recherche/?object_name=Question&format=xml

**Comment by boogheta** [comment]
C'est lié au fait que sur NosSénateurs, l'objet Question inclue également les Questions Orales. Mais il est possible de filtrer uniquement les questions écrites en ajoutant l'argument suivant : `&tag=type=question+ecrite`
Par exemple : https://www.nossenateurs.fr/recherche/?object_name=Question&tag=type=question+ecrite&format=xml
La liste des valeurs possibles du champ type est ici (à slugifier, c-a-d à mettre en minuscule, sans accents, et avec + à la place des espaces) : https://github.com/regardscitoyens/nosdeputes.fr/blob/nossenateurs.fr/config/doctrine/schema.yml#L313-L329
Les autres champs listés dans `moretags` peuvent également être employés pour plus de filtrage d'ailleurs

**Comment by malex18** [comment]
Super merci pour votre réponse.

Y a t-il une manière similaire pour nos députés ?

Sinon comment fait on pour récupérer les questions écrites des députes ?

**Comment by boogheta** [comment]
Pour les députés l'objet QuestionEcrite n'inclut bien que les questions écrites, donc pas besoin de filtrage complémentaire.
Mais il est également possible de filtrer plus finement par exemple par député avec le même genre de paramètres, à retrouver ici : https://github.com/regardscitoyens/nosdeputes.fr/blob/master/config/doctrine/schema.yml#L407

**Comment by malex18** [comment]
Pardon je me suis trompé je voulais écrire: "comment fait on pour récupérer les questions **orales** des députes ?"

J'ai vu qu'on pouvais utiliser l'object name Intervention avec le tag question, mais je n'arrive pas a partir de la a trouver simplement le texte de la question orale.

**Comment by boogheta** [comment]
Il n'y a pas vraiment d'autre moyen que cela, les questions orales sont des interventions dans les débats et peuvent avoir été entrecoupées d'interruptions.
En l'état de la base de NosDéputés.fr, le seul moyen efficace d'identifier les questions orales n'est pas dispo dans l'API et repose sur une requete SQL un peu complexe consistant à identifier les interventions longues successives d'un même parlementaire au sein d'une même sous-section de la section Questions au gouvernement.

**Comment by malex18** [comment]
Merci pour vos réponses.
