### ISSUE TITLE
Erreur 500 pour 2012-2017.nosdeputes.fr/organismes/groupe/json

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#135]
Coucou, juste pour signaler que j'ai une erreur 500 pour https://2012-2017.nosdeputes.fr/organismes/groupe/json

**Comment by boogheta** [comment]
Problème de cache lié à la migration
C'est corrigé !

**Comment by mdamien** [comment]
Merci :)
