### ISSUE TITLE
warning dans une réponse JSON (API amendements)

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#136]
Hop, si j'essaye de récupérer des amendements dans l'instance 2007-2012, ex: https://2007-2012.nosdeputes.fr/amendements/820/json, j'ai ceci en plus de la réponse JSON:

```
Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /home/nosdeputes/nd2007/lib/vendor/lexpress/symfony1/lib/user/sfBasicSecurityUser.class.php on line 257
```

**Comment by teymour** [comment]
Cette partie du code n'est pas dans le dépôt mais installé via composer (l'équivalent de pip). Pas forcement de solution idéale. La solution la plus simple que j'ai trouvé est de désactiver les warning sur cet appel de init_set :

```
--- /home/nosdeputes/nd2007/lib/vendor/lexpress/symfony1/lib/user/sfBasicSecurityUser.class.php	2020-05-24 23:54:17.565917560 +0200
+++ /home/nosdeputes/nd2007/lib/vendor/lexpress/symfony1/lib/user/sfBasicSecurityUser.class.php.new	2020-05-24 23:54:33.434040394 +0200
@@ -254,7 +254,7 @@
     // force the max lifetime for session garbage collector to be greater than timeout
     if (ini_get('session.gc_maxlifetime') < $this->options['timeout'])
     {
-      ini_set('session.gc_maxlifetime', $this->options['timeout']);
+      @ini_set('session.gc_maxlifetime', $this->options['timeout']);
     }
 
     // read data from storage
```

Je l'ai fait sur les instances 2007 et 2012. Sur la prod actuelle, on n'est pas en php7 (encore) donc pas de problème à priori.

**Comment by RouxRC** [comment]
je confirme que le Warning a bien disparu sur l'url précitée

**Comment by mdamien** [comment]
merci :)
