### ISSUE TITLE
Erreur 500 pour 2007-2012.nosdeputes.fr/seance/1050/820/json

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#137]
En faisant tourner les tests de la fabrique, j'ai trouvé cette erreur 500: https://2007-2012.nosdeputes.fr/13/seance/1050/820/json

**Comment by boogheta** [comment]
problème de cache également, corrigé

**Comment by mdamien** [comment]
super, merci !

**Comment by mdamien** [comment]
Je me suis emballé trop vite, l'erreur 500 est revenue

**Comment by mdamien** [comment]
On dirait que l'erreur revient puis repart puis revient *(comme dans les années 80)*

**Comment by boogheta** [comment]
c'est bizarre cette affaire :/ Je rouvre du coup

**Comment by mdamien** [comment]
Je pense que c'est lié, l'API `/deputes/` renvoi aussi un 500: https://2007-2012.nosdeputes.fr/deputes/json

**Comment by RouxRC** [comment]
@teymour a fait un changement de config sur le nouveau server qui devrait avoir corrigé ce souci récurrent d'erreurs 500 sur les ND 2007 et 2012, peux-tu confirmer si tu ne le rencontres plus @mdamien ?

**Comment by mdamien** [comment]
Je confirme que je n'ai plus le problème, merci @teymour !
