### ISSUE TITLE
Link to lafabriquedelaloi.fr is incorrect

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#144]
On this page for example: https://www.nosdeputes.fr/15/dossier/8841

The link is: https://www.lafabriquedelaloi.fr/articles.html?loi=15-
It should be: https://www.lafabriquedelaloi.fr/articles.html?loi=pjl19-063
Or: https://www.lafabriquedelaloi.fr/articles.html?loi=15-bioethique_2

**Comment by boogheta** [comment]
C'est lié au problème d'intégration des textes depuis janvier, le lien avec le dossier AN vient de là donc on ne l'a plus depuis
