### ISSUE TITLE
Trouver une alternative à /recherche/query_amendements qui est déprécié

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#158]
Voir https://github.com/regardscitoyens/anpy/issues/26

**Comment by David-Guillot** [comment]
Quelques pistes open data :

* La liste CSV d'amendements par dossier (exemple http://data.assemblee-nationale.fr/dossierLeg/liste-amendements?idDossier=37229) ; elle est vide (`404`) pour pas mal de dossiers récents et ça a été signalé à l'AN, et quand elle contient effectivement des amendements elle indique l'ancienne URL et pas la nouvelle, mais ça aussi ça a été signalé et la nouvelle URL pourrait arriver assez vite
* La liste complète des amendements en open data (http://data.assemblee-nationale.fr/travaux-parlementaires/amendements/tous-les-amendements) n'est plus un gigantesque fichier JSON comme à une époque mais une archive ZIP contenant un dossier par dossier législatif et, à l'intérieur, un fichier JSON par amendement

**Comment by boogheta** [comment]
On utilise déjà la liste complète en open data mais jusqu'ici on s'en servait juste pour vérifier qu'on avait rien raté par le crawl du moteur de recherche. Il va falloir que ca devienne notre source première de vérité, ça ne devrait pas être trop compliqué à adapter.

Par contre il va falloir aussi :
- soit recoder le parser pour les nouvelles pages web (pour l'instant on utilise le hack via les cookies qui permet d'afficher la page d'un amendement sur l'ancien modèle)
- soit prendre les données directement dans les json, mais de mémoire la dernière fois qu'on a voulu faire ça on avait un souci avec le dispositif certains amendements (notamment ceux des PJLF avec tableaux je crois)

**Comment by boogheta** [comment]
ha et avec réflexion le problème de la liste uniquement via l'opendata c'est la fraicheur des données, si on tient à pouvoir intégrer les amendements au plus vite, il faudrait reposer quand même en plu sur leurs listes de nouveaux documents je pense

**Comment by David-Guillot** [comment]
Oui tout à fait : 

* On n'échappera pas au scraping du nouveau format HTML car l'open data a des données géniales mais très, très difficiles à interpréter en ce qui concerne les tableaux budgétaires
* La liste que je vous indiquais dans https://github.com/regardscitoyens/anpy/issues/26 sera très utile pour combler le vide entre la dernière mise à jour de l'open data et le présent

Ne pas perdre de vue ce qui se joue dans le système d'information de l'Assemblée : le fameux nouveau pipeline de publication des données parlementaires, dont on entend parler depuis au moins 2017, est enfin opérationnel : fini Eloi qui génère directement les amendements en HTML et PDF, bonjour la base de données XML qui centralise textes et amendements pour : 

* D'une part les publier en open data XML à partir duquel sont générés le nouveau site web mais aussi les formats JSON
* D'autre part générer une sorte de log des publications/modifications, cette fameuse liste journalière (qui est quand même vachement mieux que le bus Kafka dont on nous a parlé en 2018)

Bref, ça a mis du temps, mais c'est vraiment cool ce qu'ils sont en train de finir là, à voir la fiabilité (on a déjà repéré/signalé des bugs comme par exemple un amendement absent du nouveau système alors qu'il était présent dans l'ancien ; la bonne nouvelle c'est que le nouveau système alimentant le nouveau site web, la criticité de ce genre de bugs est maximale chez eux).

**Comment by David-Guillot** [comment]
La bonne nouvelle du jour : les listes en CSV (par dossier) sont à nouveau opérationnelles, a priori on ne sera pas obligé d'utiliser le gros Zip, sauf à des fins de vérification.
