### ISSUE TITLE
Derniers dossiers non à jour via API

### ISSUE THREAD

**Issue by ghost** [regardscitoyens/nosdeputes.fr#163]
Lors d'une requête vers l'API pour obtenir les derniers dossiers débattus, je n'obtiens pas le même résultat que ce qui est affiché sur le site à cette adresse : https://www.nosdeputes.fr/dossiers/date
En requêtant l'API sur ce endpoint : https://www.nosdeputes.fr/15/dossiers/date/xml je n'obtiens pas le dossier sur la "Sécurité Globale" qui est pourtant le 1er affiché sur le site.
Comment puis-je avoir exactement les derniers dossiers tels qu'ils sont affichés sur le site ?

**Comment by RouxRC** [comment]
C'est à vérifier, mais je pense que la route de l'API ne renvoie que les dossiers pour lesquels nous avons l'association avec l'identifiant de dossier de l'Assemblée (url_institution), or celui-ci manque pour tous les dossiers initiés depuis janvier du fait du problème d'intégration des projets et propositions de loi depuis lors en cours de résolution par @teymour 
Le problème devrait alors se résoudre de lui-même à ce moment là, désolé.
Quel est votre usage ? Au besoin nous pourrions envisager d'ajouter un argument à cette route du type `?include=all` qui ne serait pas limitée aux dossiers avec url_institution

**Comment by ghost** [comment]
Je réalise une application Android qui vise à faire à peu près ce que fait votre site web.
Dans ce but, j'ai besoin des même données et sur ce point, je n'ai pas compris au premier abord la réponse API.
Maintenant, cela est clair, je n'étais pas au courant de ce problème.
Peut-être vais-je faire un crawler directement sur le site de l'AN pour compléter la réponses envoyée par l'API.
Quand pensez-vous que ce problème sera résolu ? 
Aussi, vous mentionnez dans votre doc le site ParlAPI, mais ce dernier ne fonctionne plus? Est-ce la doc qui n'est pas à jour ?

**Comment by mdamien** [comment]
Vous pouvez aussi télécharger la base de données afin de faire une API qui réponde à vos besoins: https://data.regardscitoyens.org/nosdeputes.fr/nosdeputes.fr_donnees.sql.gz

Pour parlapi, le site n'a pas encore pris en compte les modifications de format que l'AN à faite derniérement à l'Open Data et n'est donc plus à jour.

**Comment by RouxRC** [comment]
Pour ce qui est du délai de résolution je ne saurais dire, les corrections sont bien avancées mais nous sommes tous bénévoles donc c'est quand nous trouvons du temps. Mais je dirais dans les prochaines semaines

**Comment by ghost** [comment]
Merci pour vos réponses, je vais trouver un work-arround d'ici votre correction ! :)

**Comment by RouxRC** [comment]
Pour info j'ai poussé l'option include=all évoquée pour renvoyer tous les dossiers donc je ferme cette issue, mais les documents ne sont pas encore à jour même si c'est pour bientôt :)
