### ISSUE TITLE
Ajouter les emails des senateurs

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#165]
J'ai remarqué que les emails des senateurs ne sont pas présents dans les données

EDIT: Petit script utilisé pour le faire

```python
import csv
import requests
from bs4 import BeautifulSoup

for line in csv.DictReader(open('senateurs.csv'), delimiter=";"):
    if line['ancien_senateur'] != '1':
        resp = requests.get(line['url_institution'])
        soup = BeautifulSoup(resp.text, 'lxml')
        for a in soup.select('a'):
            if '@' in a.text:
                print(a.text)
                break
```

(et ensuite j'enléve le faux positif: "notices-senateurs@senat.fr")

Resultat: https://gist.github.com/mdamien/1d78f934b64f85d0c29b2fc80d677eb7

**Comment by boogheta** [comment]
Euh si les mails sont dans les données : https://www.nossenateurs.fr/senateurs/enmandat/xml

**Comment by mdamien** [comment]
ah, c'est une autre url, celle que j'utilise: https://www.nossenateurs.fr/senateurs/xml

**Comment by boogheta** [comment]
Oui ils ne sont pas dans celle là parce que c'est l'ensemble des élus y compris plus en mandat, or ceux-ci n'ont plus de mail dans l'institution
