### ISSUE TITLE
Awkward document_url response JSON formatting

### ISSUE THREAD

**Issue by Guillaume-Levrier** [regardscitoyens/nosdeputes.fr#178]
Search API yields documents as follows:

```js
{document_id: "105639",
document_type: "Amendement",
document_url: "http://www.nosdeputes.fr//api/document/Amendement/105639/json"}
```

Requesting document_url will yield an object such as:

```js
{amendement:
    {auteur_groupe_acronyme: "NI",
     auteur_id: "88",
     created_at: "2019-09-20 20:44:27",
     ...
     }
}
```

It would IMHO  make more sense to yield something like:

```js
{auteur_groupe_acronyme: "NI",
auteur_id: "88",
created_at: "2019-09-20 20:44:27",
text_type: "amendement", // add property here
      ...
}
```

This doesn't sound like much but avoiding pointless data nesting feels like a good practice in general? Having to solve this in JS or python is trivial, but much less so in lower level languages.

**Comment by RouxRC** [comment]
It would be good practice but we cannot change the existing output without breaking many existing services and taking the time to setup new routes is too much of a hassle compared to the minor inconvenience of dealing with this formatting
