### ISSUE TITLE
New parsing commissions

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/nosdeputes.fr#183]
TO CHECK/FIX
- [x] source urls not used again at the end after video one used
- [x] anchor missing in source urls for first intervention
- [x] meeting time with minutes badly parsed (9:30 => 9:00)
- [x] timestamp for videos use timecode instead of incrementing our own timestamps, making them decrease
- [x] homogeneiser les apostrophes
- [x] html styling kept should be removed ? (try to load locally first to see)
- [x] check why compute_latest generate so little new CR starting from prod status (only about 170 new CR in 18 months?)
- [x] gestion des fonctions raccourcies et association au bon intervenant quand plusieurs avec nom de début de fonction identiques : ex avec secrétaires détat et rapporteurs ici https://www.assemblee-nationale.fr/dyn/15/comptes-rendus/cion_fin/l15cion_fin1819086_compte-rendu#P24_1128

**Comment by teymour** [comment]
For the video issue, this commit should solve it : baf51fa

**Comment by teymour** [comment]
Timestamp pb : 1796e2eb1cb21d09f04aa5be84eabf5a7dd94417

**Comment by RouxRC** [comment]
https://www.assemblee-nationale.fr/15/cr-cafe/21-22/c2122007.asp
- [x] une intervention manquée (parce que M. manquant?) : `<p><b>Jacques Maire (LaREM).</b> Le groupe La République en Marche a pris, en début de législature`
- [x] plusieurs intervenants sont rendus avec leur groupe entre parenthèses par ex `Alain David (SOC)`, `Sonia Krimi (LaREM)` (c'est dans tous les CRs de cette commission)

**Comment by RouxRC** [comment]
Pour info j'ai pushé un script qui prend une url source et fait tout (download + parsing) et renvoie optionnellement le rapport de contrôle que j'utilisais avant, ça permet d'identifier les bugs visuellement assez facilement : 
ça se lance par exemple comme ça : 
`./compute_one.sh https://www.assemblee-nationale.fr/15/cr-cafe/21-22/c2122007.asp 1`

**Comment by RouxRC** [comment]
https://www.assemblee-nationale.fr/15/cr-cafe/21-22/c2122011.asp
- [x] le sommaire de la vidéo chargée contient à la fois de l'inédit (la seconde partie mission d’information) et du déjà présent au CR (la résolution européenne)

Là je n'ai pas de solution automatisée vraiment envisageable honnetement, ça fait partie des raisons pour lesquelles j'avais arrêté de laisser les commissions se charger toutes seules et je nettoyais ces fichiers parsés là à la mano.

**Comment by RouxRC** [comment]
https://www.assemblee-nationale.fr/15/cr-cdef/21-22/c2122010.asp
et https://www.assemblee-nationale.fr/15/cr-cdef/21-22/c2122014.asp
et partiellement seulement dans https://www.assemblee-nationale.fr/15/cr-cdef/21-22/c2122016.asp (certaines personnalités bien reconnues)

- [x] les autres intervenants que députés ne sont pas détectés comme tels dans le sommaire de la vidéo, j'avais une regexp dégueulasse qui s'en sortait pas mal avant, je ne sais pas trop si y a beaucoup mieux de faisable
- [x] par ailleurs un strip des espaces successifs aurait globalement du sens on dirait
```-> <p><h4>CGA Olivier Schmit, secrétaire général du CSFM                       </h4></p>
-> <p><h4>Capitaine Christophe, secrétaire du conseil     </h4></p>
-> <p><h4>Questions des représentants des groupes</h4></p>
-> <p><h4>Capitaine Christophe, secrétaire du conseil     </h4></p>
-> <p><h4>Adjudant Stéphane, secrétaire adjoint du conseil            </h4></p>
-> <p><h4>Commandant Anne-Lise</h4></p>
-> <p><h4>Commissaire en chef de 1ère classe Sammy</h4></p>
-> <p><h4>Sergent-chef Nicolas</h4></p>
-> <p><h4>Major Jean-Michel</h4></p>
-> <p><h4>Commissaire en chef de 1ère classe Sammy</h4></p>
-> <p><h4>Caporal-chef de 1ère classe Sandrine</h4></p>
-> <p><h4>Capitaine Christophe, secrétaire du conseil     </h4></p>
-> <p><h4>Caporal-chef de 1ère classe Sandrine</h4></p>
-> <p><h4>Commandant Anne-Lise</h4></p>
-> <p><h4>Commissaire en chef de 1ère classe Sammy</h4></p>
-> <p><h4>Infirmier en soins généraux de 2ème classe Jean-Philippe</h4></p>
-> <p><h4>Questions des députés</h4></p>
-> <p><h4>Commissaire en chef de 1ère classe  Alain</h4></p>
-> <p><h4>Infirmier en soins généraux de 2ème classe Jean-Philippe</h4></p>
-> <p><h4>Premier maître Frédéric</h4></p>
-> <p><h4>Adjudant Stéphane             </h4></p>
-> <p><h4>Major Jean-Michel</h4></p>
-> <p><h4>Capitaine Christophe, secrétaire du conseil     </h4></p>
-> <p><h4>Sergent-chef Nicolas</h4></p>
-> <p><h4>Commissaire en chef de 1ère classe Sammy</h4></p>
-> <p><h4>Caporal-chef de 1ère classe Sandrine</h4></p>
-> <p><h4>Major Jean-Michel</h4></p>
-> <p><h4>Capitaine Christophe, secrétaire du conseil     </h4></p>
-> <p><h4>Major Jean-Michel</h4></p>
-> <p><h4>Commandant Anne-Lise</h4></p>
-> <p><h4>Caporal-chef de 1ère classe Sandrine</h4></p>
-> <p><h4>Commissaire en chef de 1ère classe  Alain</h4></p>
```

**Comment by teymour** [comment]
> https://www.assemblee-nationale.fr/15/cr-cafe/21-22/c2122007.asp
>     * [ ]  plusieurs intervenants sont rendus avec leur groupe entre parenthèses par ex `Alain David (SOC)`, `Sonia Krimi (LaREM)` (c'est dans tous les CRs de cette commission)

Pour moi, ce n'est pas vraiment un problème car c'est bien intégré au load.

**Comment by teymour** [comment]
> https://www.assemblee-nationale.fr/15/cr-cafe/21-22/c2122012.asp
> 
>     * [ ]  le sommaire de la vidéo chargée contient à la fois de l'inédit (la seconde partie mission d’information) et du déjà présent au CR (la résolution européenne)
> 
> 
> Là je n'ai pas de solution automatisée vraiment envisageable honnetement, ça fait partie des raisons pour lesquelles j'avais arrêté de laisser les commissions se charger toutes seules et je nettoyais ces fichiers parsés là à la mano.

Je pense que le lien n'est pas bon. Je ne vois pas de vidéo dans ce compte rendu.

**Comment by RouxRC** [comment]
Ha oui pardon c'était le précédent, je corrige dans le précédent commentaire.

**Comment by teymour** [comment]
>     * [ ]  check why compute_latest generate so little new CR starting from prod status (only about 170 new CR in 18 months?)

En augmentant le nombre de page ici https://github.com/regardscitoyens/nosdeputes.fr/blob/master/batch/commission/download_commission.pl#L11 (200) j'ai testé avec plus de 800 CR sur 2020-2021 et 2021-2022

**Comment by teymour** [comment]
> [ ] le sommaire de la vidéo chargée contient à la fois de l'inédit (la seconde partie mission d’information) et du déjà présent au CR (la résolution européenne)

Ajouté des warnings 08a42899272fc29e5600f60d7bf53ae04aa8a5cb
