### ISSUE TITLE
Documentation accès aux scrutins/votes par l'API?

### ISSUE THREAD

**Issue by lucgiffon** [regardscitoyens/nosdeputes.fr#185]
Hello,

je crois que la documentation de l'API (https://github.com/regardscitoyens/nosdeputes.fr/blob/master/doc/api.md) ne fait pas de référence à comment accéder aux votes des parlementaires, ni à partir d'un scrutin, de trouver les parlementaires ayant voté. A ajouter? Je peux le faire.

En fouinant, j'ai bien compris qu'il suffisait de rajouter /xml à l'url de la page intéressante du site (`https://www.nosdeputes.fr/15/scrutin/4195` -> `https://www.nosdeputes.fr/15/scrutin/4195/xml`).

Sinon bravo pour le job, j'étais en train de me casser les dents sur les données brutes de l'AN avant de tomber sur votre API. Je me disais que ça serait bien que ça existe. Ceci dit, je trouve qu'elle est un peu difficile à trouver. 

Merci en tous cas
++

**Comment by boogheta** [comment]
Hello @lucgiffon et bien vu, merci !
C'est dans la [roadmap des votes](https://github.com/regardscitoyens/nosdeputes.fr/issues/121) en fait et n'a pas encore été fait parce que plus de fonctionnalités de l'API manquent encore mais celles déjà présentes mériteraient d'être documentées clairement ! N'hésite pas à proposer une PR. Pour l'instant les 3 routes existantes sont (modulo xml/json/csv) :
- un scrutin https://www.nosdeputes.fr/16/scrutin/1/xml
- les scrutins d'un parlementaire https://www.nosdeputes.fr/bruno-duverge/votes/xml
- et tous les scrutins https://www.nosdeputes.fr/16/scrutins/xml mais apparemment cette route est cassée car trop gourmande en ram en cette fin de législature donc à oublier dans un premier temps je pense

Merci !

**Comment by lucgiffon** [comment]
Fixed in https://github.com/regardscitoyens/nosdeputes.fr/pull/201
