### ISSUE TITLE
Problème d'import des données de députés - Propriété undefined

### ISSUE THREAD

**Issue by maximerivolet** [regardscitoyens/nosdeputes.fr#190]
Bonjour,

Depuis 2 jours, nous n'arrivons plus à faire l'import des données. Après avoir vérifié sur une URL en direct (pour exemple : https://www.nosdeputes.fr/damien-abad/graphes/lastyear/total?questions=true&format=json), j'observe des undefined directement dans les données : 

![image](https://user-images.githubusercontent.com/12681339/167845109-7e8d23c7-d31e-4de7-b4b1-fda279c597f6.png)
![image](https://user-images.githubusercontent.com/12681339/167845154-08ed4ea0-7016-42dd-bd32-8814a05c1f60.png)

Il y a très peu de valeur de défini, et peu d'homogénéité. (Sep, Jan 18, Mai, ...)

Avez-vous fait des modifications sur les données récemment ?

Cordialement,

**Comment by boogheta** [comment]
Bonjour,
Le site a basculé en mode législature complète, c'est pourquoi il y a désormais 255 labels (semaines) et non plus une cinquantaine. Le champ label sert à peupler les labels de l'axe du temps des graphiques et c'est pourquoi il n'y a que peu de labels pour qu'ils ne se chevauchent pas : https://nosdeputes.fr/damien-abad

Je vous recommande par ailleurs de basculer plutot sur les routes des données complètes : https://www.nosdeputes.fr/damien-abad/graphes/legislature/total?questions=true&format=json

**Comment by boogheta** [comment]
Et plus globalement je vous encourage à éviter d'utiliser ces routes dont le but est vraiment uniquement d'alimenter nos graphiques, vous devriez plutot reconstituer les agrégats de votre choix à partir des données mensuelles plus brutes sur les routes d'api publique documentées ici : https://github.com/regardscitoyens/nosdeputes.fr/blob/master/doc/api.md#donn%C3%A9es-dactivit%C3%A9-des-parlementaires

**Comment by maximerivolet** [comment]
Bonjour,

Je reviens vers vous concernant ce sujet. J'ai regardé un peu ce qui est disponible pour les données d'activité. Les données au mois ne sont pas assez précises. En effet, les données stipulées dans l'adresse ci-dessous nous permettent d'avoir des données à la semaine : https://www.nosdeputes.fr/damien-abad/graphes/lastyear/total?questions=true&format=json

Nous utilisons ces données également pour afficher sur un graphe. Dans ce contexte, à part utiliser la route mentionnée ci-dessus (https://www.nosdeputes.fr/damien-abad/graphes/legislature/total?questions=true&format=json), nous n'avons pas d'autre choix, c'est bien ça ?

**Comment by boogheta** [comment]
Non dans ce cas je pense que c'est votre seule solution, à moins de régénérer vos propres données à partir de nos dumps sql

**Comment by maximerivolet** [comment]
Du coup avec cette URL, on a les 256 semaines de la législature. Comment ça se passera au début de la prochaine ? Les API renverront pour les nouveaux députés 256 valeurs vides, qui se rempliront au fur et à mesure des semaines ?

**Comment by boogheta** [comment]
Non on sera de nouveau en mode législature normale, et même en mode début de législature, donc il n'y aura que les premières semaines et ca grossira semaine après semaine jusqu'à atteindre un an comme auparavant

**Comment by boogheta** [comment]
(désolé c'est pas très consistant, je sais, mais en même temps vous n'utilisez pas vraiment une API conçue pour d'autres usages que ceux internes du site)

**Comment by maximerivolet** [comment]
C'est noté, merci pour les retours c'est très clair. Je me permets de fermer l'issue.
