### ISSUE TITLE
mise a jour de la documentation opendata

### ISSUE THREAD

**Issue by petitkriket** [regardscitoyens/nosdeputes.fr#193]
Hello,

Je me suis servi de la liste de parlementaires en open data JSON mise a disposition [sur le fichier de doc open data](https://github.com/regardscitoyens/nosdeputes.fr/blob/master/doc/api.md#liste-des-parlementaires) pour faire [une application](https://dazzling-lily-0c2066.netlify.app/) pour le plaisir

Je me demandais si les données des parlementaires elus tout recemment son également disponibles a ce format ou exposés sur une API ? Je n'ai pu trouver qu'un jeu de fiches distinctes sur le site de [l'assemblée nationale](https://data.assemblee-nationale.fr/acteurs/deputes-en-exercice)

Est ce que je peux aider si c'est pas le cas ?

**Comment by RouxRC** [comment]
Bonjour @petitkriket, NosDéputés.fr a été mis à jour pour la 16ème législature en fin de semaine dernière, vous pouvez donc désormais trouver les données sur les nouveaux députés à l'adresse que vous avez employée, tandis que les données que vous aviez utilisées se trouvent désormais à la même adresse en remplaçant "www" par "2017-2022"

**Comment by petitkriket** [comment]
merci ! bonne journée !
