### ISSUE TITLE
Issues regarding the data dumps required to deploy the website

### ISSUE THREAD

**Issue by francesco-gramegna** [regardscitoyens/nosdeputes.fr#199]
In order for the website to work, it is needed that we download a dump of data to proprely initialize the db.
However the link https://www.regardscitoyens.org/publication/#donnees is down and so no dumps are availables.
Is there anyone who has downloaded such dump and that could post it somewhere so that the db can be initialized and the website can be deployed?

**Comment by francesco-gramegna** [comment]
The site is back up online and i have managed to do an backup of a data dump.

**Comment by RouxRC** [comment]
Sorry about this,the main Regards Citoyens server was down due to OVH as well as all servers located in the same room for a few days.
