### ISSUE TITLE
DB item type inconsistency ("parlementaire" & "depute").

### ISSUE THREAD

**Issue by Guillaume-Levrier** [regardscitoyens/nosdeputes.fr#203]
I'm doing the query "dragon" on the "2007-2012" legislature.

`https://2007-2012.nosdeputes.fr/recherche/dragon?format=json`

Mapping documents by type gets me:
- 2 texteloi
- 8 intervention
- 9 questionecrite
- 1 parlementaire

I need to retrieve the documents for my research, which I do using the API. 

I am use to getting answers like :
`{doctype : {…}}`

So for example, if I'm querying a questionecrite, I will get an answer like:
`{questionecrite: {…}}`

✨ **_HOWEVER_** ✨

If the document type is a _parlementaire_, then the answer will be _depute_:
<img width="638" alt="Capture d’écran 2024-11-14 à 14 32 33" src="https://github.com/user-attachments/assets/382eca45-4f6d-459b-8698-1863e24bdf21">

Can I solve this on my own by letting my own system know that a depute is a parlementaire? Yes.

Do I think this API be consistent with itself and choose between depute and parlementaire? Also yes, but maybe someone will convince me otherwise?

**Comment by boogheta** [comment]
the suggestion makes sense, but the project being closed and in order to ensure maintenance of existing services, changing this is definitely a nogo
