### ISSUE TITLE
CORS issue on the séance JSON file fetching

### ISSUE THREAD

**Issue by Guillaume-Levrier** [regardscitoyens/nosdeputes.fr#204]
I am trying to locally fetch specific séances which contain expressions I am looking for.

Here is the message I get.

I can solve this for myself, but I am building a software that automates it for researchers (and, through this means, help make research easily reproducible), and my guess that this new problem comes with the security restrictions that come with the newer versions of the [electron framework](https://www.electronjs.org/).

> Access to fetch at 'https://www.nosdeputes.fr/seance/229/json' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by boogheta** [comment]
I believe that's because you're calling https from http which is a standard security rule from all browsers

**Comment by Guillaume-Levrier** [comment]
Alright then it's a me problem, thank you !
