### ISSUE TITLE
Uncaught Error: Class 'DOMDocument' not found

### ISSUE THREAD

**Issue by nathanncohen** [regardscitoyens/nosdeputes.fr#3]
Hello,

I was not able to make it very far in my attempt to setup NosDeputes.fr. Here is what I get when I run `php -S localhost:8080 -t web/` then load the front page.

    [Sun Apr  2 07:06:54 2017] PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /home/ncohen/nosdeputes.fr/apps/frontend/modules/circonscription/actions/actions.class.php:255

The las thing I did was run `php symfony doctrine:build --all --no-confirmation`, which did not report anything wrong. I have not downloaded any 'data' for the moment, and I worry a bit about that: http://dev.nosdeputes.fr/ asks me for a password.

Thanks,

Nathann

**Comment by nathanncohen** [comment]
Solved by installing `php-dom` as advised on http://stackoverflow.com/questions/14395239/class-domdocument-not-found.

Everything runs fine now, except I don't have any data (yet). Sorry for the noise,

Nathann

**Comment by RouxRC** [comment]
Never encountered it, but good to know, maybe add a pointer to  it in the readme :)
