### ISSUE TITLE
Unknown record property

### ISSUE THREAD

**Issue by nathanncohen** [regardscitoyens/nosdeputes.fr#4]
Hello,

In the process of setting up a local server running nosdeputes.fr, I now find myself stuck when I try to load the page of a MP. I previously imported the data alright. Here is what happens when I load `http://localhost:8080/yves-fromion`
```
[Sun Apr  2 07:30:46 2017] Unknown record property / related component "<pre>
alias : Texteloi
foreign : id
local : texteloi_id
class : Texteloi
type : 0
table : Object(TexteloiTable)
localTable : Object(ParlementaireTexteloiTable)
name : 
refTable : 
onDelete : 
onUpdate : 
deferred : 
deferrable : 
constraint : 
equal : 
cascade : Array
owningSide : 
refClassRelationAlias : 
foreignKeyName : 
orderBy : 
</pre>" on "ParlementaireTexteloi"
[Sun Apr  2 07:30:46 2017] ::1:54658 [500]: /yves-fromion
[Sun Apr  2 07:30:46 2017] ::1:54660 [404]: /sf/sf_default/css/screen.css - No such file or directory
[Sun Apr  2 07:30:46 2017] ::1:54662 [404]: /sf/sf_default/images/sfTLogo.png - No such file or directory
[Sun Apr  2 07:30:46 2017] ::1:54664 [404]: /sf/sf_default/images/icons/tools48.png - No such file or directory
[Sun Apr  2 07:30:46 2017] ::1:54666 [200]: /favicon.ico
```

I seem to have gone through all steps of `http://cpc.regardscitoyens.org/trac/wiki/Installation`, with the exception of the Tomcat/SolR section. Indeed, I have no `lib/vendor/SolrServer` directory on my computer, and only a `lib/vendor/SolrClient`. I do not know whether that is the problem, though.

Thanks,

Nathann

**Comment by RouxRC** [comment]
You shouldn't require Solr to get something working, this will only block the search module and parts of the api.
it looks to me like your issue comes from /sf/ not being properly redirected. When serving with apache, we have the following directive that serves a specific folder under /sf:
```
      Alias /sf "NDPATH/lib/vendor/symfony/data/web/sf"
      <Directory "NDPATH/lib/vendor/symfony/data/web/sf">
        AllowOverride All
        Allow from All
      </Directory>
```

Maybe you can try to solve it by simply adding a symbolic link in your ND root directory:
```bash
ln -s NDPATH/lib/vendor/symfony/data/web/sf NDPATH/sf
```

Also, when deving locally, you should use frontend_dev.php in your urls (for instance : http://localhost:8080/frontend_dev.php/yves-fromion )

**Comment by nathanncohen** [comment]
I applied this and created the symbolic link. It was working fine yesterday, and I am now stuck with the same error again, trying to figure out what the source may be :-/

**Comment by revolunet** [comment]
can this be closed ?

**Comment by RouxRC** [comment]
I don't belive anyone else hast encountered it again since and the installation has changed a bit since we migrated to php7 so yes let's close and reopen if someones encounters it again
