### ISSUE TITLE
Prepare first data députés 2017

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/nosdeputes.fr#45]
- [x] nom 
- [x] nom_de_famille
- [x] sexe
- [x] date de naissance
- [x] profession
- [x] twitter (complete missing from liberation + ancienne législature)
- [x] sites web (complete missing from liberation + ancienne législature)
- [x] url ancien cpc
- [x] rattachement financier (complete from alphoenix scrap of pdf beauvau)
- [x] lowercase rattachements financiers
- [x] cleanup doublons sites web

useful : 
- wikipedia : https://fr.wikipedia.org/wiki/Liste_des_d%C3%A9put%C3%A9s_de_la_XVe_l%C3%A9gislature_de_la_Cinqui%C3%A8me_R%C3%A9publique
- beauvau : https://www.data.gouv.fr/s/resources/elections-legislatives-des-11-et-18-juin-2017-resultats-du-2nd-tour/20170619-090431/Leg_2017_Resultats_T2.xlsx  https://www.data.gouv.fr/s/resources/elections-legislatives-des-11-et-18-juin-2017-resultats-du-2nd-tour/20170620-101625/Leg_2017_Resultats_T2_c.xlsx  liste élus par mail
- libé : http://www.liberation.fr/apps/2017/06/profil-nouvelle-assemblee-legislative/data/SecondTour2.csv?23286859639558388
- twitter : https://twitter.com/TwitterPolFR/lists/d-put-s-2017-22?s=09
- le monde : https://docs.google.com/spreadsheets/d/1HhbEM3Wksm6Z5CnNd5N9yomgnXacQsYoXFjTw9TBECM/edit#gid=2034211089
- AN : http://www2.assemblee-nationale.fr/elections/liste/2017/resultats/RESULTAT
- calendrier groupes/commissions/fonctions : http://www2.assemblee-nationale.fr/14/le-bureau-de-l-assemblee-nationale/comptes-rendus-et-convocation/2017/reunion-du-mercredi-22-fevrier-2017#Ouverture
- crowdsourced https://framacalc.org/Legislatives2017_Nouveaux_deputes

**Comment by teymour** [comment]
Pour la gestion des anciennes url de ND : 3cfd92fa41c68ff8351f52c78bfe2794a1685089
