### ISSUE TITLE
Comment mieux rendre compte des différences présences / participations 

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/nosdeputes.fr#58]
**Tenir compte des amendements proposés (premier auteur) dans l'indicateur des semaines d'activité ?**

Des avis @teymour @tarNeFyS @njoyard @massiliane @kerneis @fmassot ?

**Comment by kerneis** [comment]
C'est un point qui peut potentiellement faire débat. Est-ce que c'est possible de faire quelques queries quick and dirty pour évaluer :
- pour combien de députés ça changerait quelque chose ?
- pour ces députés, de combien ça changerait (bref, comparer un histogramme du nombre de semaines d'activités avec et sans la modif) ?
- prendre quelques exemples de ceux pour qui ça change le plus et regarder en détail leurs amendements ces semaines là.
Je pense que c'est important parce qu'on peut imaginer dans l'abstrait autant de bonnes raisons de le mettre (prend en compte la diversité du travail parlementaire, ne pénalise pas les députés qui bossent sur des amendements mais ont finalement une bonne raison de ne pas pouvoir les défendre en séance) que de l'exclure (c'est le collab qui écrit pour de vrai, la date de dépôt n'est pas forcément la date où l'amendement a été le plus travaillé — exemple extrême, on ne va clairement pas prendre en compte les dates de dépôt des rapports pour des semaines d'activités). Évaluer l'impact potentiel et quelques exemples aiderait à savoir si ça vaut le coup ou non de rajouter cette complexité, j’ai l'impression.

**Comment by Massiliane** [comment]
Si je comprends bien ca voudrait dire qu'on considère que quand un député dépose un amendement on considère qu'il a eu une activité pour la semaine ? Si c'est le cas je pense que c'est effectivement une idée qui se discute. Mais je rejoins @kerneis il faut qu'on détermine quel impact de cette modification (notamment pour s'assurer que les comparaisons sont pas complètement HS entre deux législatures ?).

**Comment by teymour** [comment]
Pour moi, la semaine d'activité reflète une activité physique au parlement : lorsqu'on annonce une semaine pour un député, nous n'avons aucune doute qu'il a été effectivement présent cette semaine ci.

Pour être le premier signataire, avoir de bons collaborateurs qui posent des amendements est suffisant. 

Si il est éventuellement pertinent en tant qu'indicateur non affiché, il sera totalement dévoyé à terme en poussant les députés à demander à leurs collabs de déposer des amendements WTF en tant que premier signataire simplement pour avoir une semaine de présence supplémentaire.

**Comment by RouxRC** [comment]
En fait avec le recul, je ne pense plus non plus que ce soit une bonne idée, l'activité relative au dépot d'un amendement a lieu lors de sa défense et est donc déjà comptabilisée quand elle est réelle. Oublions :)

Par contre se pose toujours la question de comment changer la page du député pour mieux refléter qu'on n'indique pas la présence en hémicycle, mais uniquement des prises de parole, et des présences en commission (j'ai édité le titre de l'issue en conséquence).

Les pistes que j'imagine jusqu'ici et essaierait d'implémenter un we prochain : 
- remplacer les `indicateurs interventions en commission` et `interventions longues en hémicycle` en `mots prononcés en commission` et `mots prononcés en hémicycle` dans la page député (dans la synthèse ajouter les mots et garder les interventions pour assurer la rétrocomparaison)
- changer ce qu'on affiche sur le graphe : afficher juste un graphe des mots prononcés en commission et hémicycle stackés avec des couleurs différentes et toujours les QO en taquets bleus sur la page du député, et dans le détail des graphes au clic afficher deux graphes séparés des mots prononcés en hémicycle et commission, et le graphe actuel des présences et participations en commission

Avis bienvenus à nouveau ;)

**Comment by RouxRC** [comment]
obsoleted by #115
