### ISSUE TITLE
Invalid urls returned by the /amendements/xxx/json endpoint

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#83]
[This API call ](https://2007-2012.nosdeputes.fr/amendements/2636/json?textplain=true) returns urls like: http://2007-2012.nosdeputes.framendement/2636/1 (with a `/` missing after `.fr`)

**Comment by boogheta** [comment]
only existing on 2007-2012 due to missing /LEGISLATURE/ in urls, fixed in old code base
