### ISSUE TITLE
API amendments - Nothing returned but they exists in the AN website

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#87]
For those, http://www2.assemblee-nationale.fr/recherche/archives_resultats_amendements?NUM_INIT=2449&LEGISLATURE=13

I'm not getting any here: https://www.nosdeputes.fr/13/amendements/2449/json?cache=5882

**Comment by boogheta** [comment]
Although they are well there : https://2007-2012.nosdeputes.fr/amendements/2449/xml

Issue comes from our yesterday fix with 404 results which now they are caught are not redirected anymore to previous legislature, I will have a look

**Comment by mdamien** [comment]
Thanks, also I'm getting a 500 here: https://www.nossenateurs.fr/seance/1323/20082009-553/json?cache=5627 , maybe that's related

EDIT: Also on the [/seances/ endpoint](https://2017-2022.nosdeputes.fr/seances/120/json?hemicycle=1&cache=8214), maybe that's just me DDoSing the server.

**Comment by boogheta** [comment]
pour NS la même requete m'a renvoyé un 200, donc je penche pour le DDOS, le server de NS est vraiment pas bon
