### ISSUE TITLE
Idée - API interventions - Renvoyer le groupe de l'intervenant pour la législature demandée

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#88]
Lorsque l'on demande les interventions pour une ancienne legislature, le groupe renvoyé pour les intervenant est celui de la legislature en cours à la place de celui de la législature au moment de l'interventions.

example: https://www.nossenateurs.fr/seance/332/20102011-092/json?cache=test&textplain=1 (on y trouve des groupes LR ou encore LREM)

Mais l'infos est dans `/organismes/groupe/json`, alors on peut toujours se debrouiller sans

EDIT: Du coup, c'est fait pour les députés mais pour les sénateurs ce sera plus complexe je pense

**Comment by boogheta** [comment]
C'est plus compliqué que cela : les parlementaires changent de groupe aussi en cours de législature.
Nous n'historisons l'appartenance aux groupes que depuis la législature actuelle. C'est-à-dire que depuis 2017, les interventiosn ont un champ groupe correspondant au groupe à l'instant où l'intervention est prononcée. Pour les 2 précédentes, on va essayer de rajouter l'info a posteriori. Pour le Sénat pas de solution envisagée en l'état
