### ISSUE TITLE
Parsing Interventions - "Avant l'article 1era"

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/nosdeputes.fr#89]
Voila un petit bug sur le parsing des interventions, l'espace est mangé dans le titre de cette section: https://2007-2012.nosdeputes.fr/seance/3669#table_10383

**Comment by boogheta** [comment]
corrigé à la mano en base de 2007-2012 pour tous les articles 1era, 1erb, 2a, 2b, etc
