### ISSUE TITLE
[API] Gérer redirections par législature sur routes dossiers

### ISSUE THREAD

**Issue by Stephanevg** [regardscitoyens/nosdeputes.fr#92]
Bonjour,

D'abord, chapeau pour vôtre travail. Je suis fan!

Je pense avoir trouver un petit bug. Sauf erreur de ma part,  les trois liens suivants dans votre api.md semblent ne rien retourner:

Triés dans l'ordre alphabétique : https://www.nosdeputes.fr/15/dossiers/nom/xml
Triés du plus récent au plus ancien : https://www.nosdeputes.fr/15/dossiers/date/xml
Triés du plus débattu au moins débattu : https://www.nosdeputes.fr/15/dossiers/plus/xml

J'ai également éssayé la 14 et 13 eme législature (en remplacant 15 par 14 ou 13). 
/json retourne également un objet vide.

Cdlt

Stéphane

**Comment by RouxRC** [comment]
Bonjour, bien vu en effet, merci !

Les liens ne sont tout simplement pas les bons, le numéro de législature n'est pas à inclure dans ces urls, il faudrait que nous ajoutions la redirection vers le bon domaine, mais en attendant, tu pourras trouver ces données pour la 15ème aux urls suivantes, que je vais éditer de suite dans api.md : 
https://www.nosdeputes.fr/dossiers/nom/xml
https://www.nosdeputes.fr/dossiers/date/xml
https://www.nosdeputes.fr/dossiers/plus/xml

En revanche comme cela est explicitement indiqué dans api.md, cette route n'existe que depuis la 15ème législature , il est donc normal que cela ne fonctionne pas pour les 13ème et 14ème, et nous n'avons a priori pas prévu de rétroporter cette fonctionnalité

Pour la 16ème législature, a priori, elle ne commencera qu'en 2022 ;)

**Comment by Stephanevg** [comment]
Top! Merci pour cette super réactivité!

**Comment by RouxRC** [comment]
je reouvre parce qu'il reste quelque chose à faire quand meme :)

edit: désormais les 2 formes d'urls sont fonctionnelles
