### ISSUE TITLE
Access aux données de statistique d'un vote de loi via l'API

### ISSUE THREAD

**Issue by Stephanevg** [regardscitoyens/nosdeputes.fr#93]
Bonjour,

Je me posais la question si les données statistiques des lois passées (ou rejetées) sont disponibles via l'API?

Pour citer un exemple -> http://www2.assemblee-nationale.fr/scrutins/detail/(legislature)/15/(num)/365

Sauf erreur de ma part, il ne me semble pas l'avoir vu. (Ou bien est-ce pas documenté?)

Quoi qu'il en soit, ce type de données serait intressant à avoir, surtout le vote des parlementaires pour une loi bien précise. 

Super boulot!

Stéphane

**Comment by RouxRC** [comment]
Bonjour,
Non comme détaillé dans #17 les votes ne sont pas encore intégrés à NosDéputés. L'absence de publication des délégations de vote a longtemps freiné nos efforts en ce sens mais le changement prochain annoncé changera probablement ça  ;)
https://twitter.com/RegardsCitoyens/status/956213689702604806
