### ISSUE TITLE
Lister tous les Textes de lois

### ISSUE THREAD

**Issue by Stephanevg** [regardscitoyens/nosdeputes.fr#97]
(re) Bonsoir,

Est-il possible de lister TOUS les texte de lois? Aujourd'hui, l'API ne permet QUE de récuperer un texte de loi bien precis par id.

Ca serait interessant de pouvoir les lister tous (comme pour les deputes par exemple). Combiné avec https://github.com/regardscitoyens/nosdeputes.fr/issues/96 on pourait par exemple filtrer sur toutes les lois qui ne sont pas passé par exemple.

Idéalement, je verrais bien une url de ce format la:

https://www.nosdeputes.fr/api/document/Textelois/<format>

Cdlt

**Comment by RouxRC** [comment]
Là encore ce serait une route d'API qui pourrait être ajoutée ;)
Pour autant, j'ai le sentiment que cet usage est déjà réalisable, bien qu'un peu péniblement, par l'usage de l'API de la recherche https://www.nosdeputes.fr/recherche/?object_name=Texteloi&format=xml&sort=1

**Comment by Stephanevg** [comment]
Hehe, Décidement, moi avec mes mêmes types de questions ;) 

Ha oui, j'ai pas encore regarder ce que la recherche permetais de retourner, mais ton exemple est exactement ce que je recherchais à faire. (Bien que le retour soit peu à première vue, mais j'imagine qu'elle est raccourcie due à la pagination)

**Comment by RouxRC** [comment]
Oui c'est pour cela que c'est un peu pénible, les résultats étant spartiates et la pagination étant figée à 20 ce qui n'aide pas beaucoup :p Là aussi y aurait des choses à faire... :/

**Comment by Stephanevg** [comment]
Oui, c'est embêtant éffectivement.
Bon, sans trop connaître tout le mécanisme interne de la recherche, ne serait-t-il pas possible de fournir une option style: "pagination=none" lors de la requête http, et hop! il nous retournerait le tout?  :D

**Comment by RouxRC** [comment]
Le none risque de poser des soucis de ram, mais un argument count manquait clairement.
Ce n'était pas grand chose et ça trainait dans une todo, tu m'as motivé ;) C'est en prod, avec une limite max de 500 : https://www.nosdeputes.fr/recherche/?object_name=Texteloi&format=xml&count=500

**Comment by Stephanevg** [comment]
Top!! merci pour la super réactivité. Il y a une petite erreur qui c'est glissé dans chaque URL (un double "//") 

![image](https://user-images.githubusercontent.com/6302961/36385744-b806b314-1593-11e8-85ad-8df9b901e44e.png)

Peut être due à l'heure tardif du changement? ;)

(Il faut que je j'ouvre une autre issue, ou ça ira ici?)

**Comment by RouxRC** [comment]
Non ça date d'avant et c'est un effet de bord lié à autre chose qui n'a pas de conséquence problématique (les urls avec 2 slashs marchent aussi) et n'a du coup jamais été plus investigué

**Comment by Stephanevg** [comment]
Ha oui tiens c'est curieux, ma requete HTTP passe et retourne un résultat sans erreur malgré le double "//".
Curieux.
